# Generated by Django 5.1.4 on 2025-04-12 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='智能体名称')),
                ('agentID', models.CharField(max_length=30, verbose_name='智能体编号')),
                ('function', models.TextField(blank=True, null=True, verbose_name='功能描述')),
                ('photo', models.ImageField(upload_to='agent/%Y_%m_%d', verbose_name='智能体照片')),
                ('status', models.IntegerField(choices=[(1, '待机'), (2, '工作'), (3, '完成工作'), (4, '充电')], default=1, verbose_name='当前状态')),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '智能体',
                'verbose_name_plural': '智能体',
                'ordering': ('-publishDate',),
            },
        ),
    ]
