# Generated by Django 5.1.4 on 2025-04-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutApp', '0003_alter_award_options_alter_award_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'verbose_name': '成果简介', 'verbose_name_plural': '成果简介'},
        ),
    ]
