# Generated by Django 5.1.4 on 2025-04-11 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-publishDate',), 'verbose_name': '案例演示', 'verbose_name_plural': '案例演示'},
        ),
        migrations.AlterModelOptions(
            name='productimg',
            options={'verbose_name': '案例图片', 'verbose_name_plural': '案例图片'},
        ),
        migrations.AddField(
            model_name='productimg',
            name='video',
            field=models.FileField(blank=True, upload_to='ProductVideo/', verbose_name='案例视频'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='案例详情描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('智慧康养', '智慧康养'), ('智慧教育', '智慧教育'), ('智慧校园', '智慧校园')], max_length=50, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50, verbose_name=' 案例标题'),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Product/', verbose_name='案例图片'),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productImgs', to='productsApp.product', verbose_name='案例演示'),
        ),
    ]
