# Generated by Django 5.1.4 on 2025-04-11 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('phoneID', models.CharField(max_length=30, verbose_name='身份证号')),
                ('sex', models.CharField(default='男', max_length=5, verbose_name='性别')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('photo', models.ImageField(upload_to='contact/recruit/%Y_%m_%d', verbose_name='个人照片')),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '注册信息',
                'verbose_name_plural': '注册信息',
                'ordering': ('-publishDate',),
            },
        ),
    ]
