# Generated by Django 5.1.4 on 2025-04-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='phoneID',
            field=models.CharField(max_length=30, verbose_name='电话号码'),
        ),
    ]
