# Generated by Django 5.1.4 on 2025-04-14 01:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realApp', '0002_alter_resume_phoneid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '心理状态'), (2, '行为状态')], default=1, verbose_name='预警类型')),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='提交时间')),
                ('content', models.TextField(blank=True, null=True, verbose_name='预警描述')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image_warning/alerts/%Y_%m_%d', verbose_name='预警照片')),
                ('video', models.FileField(blank=True, null=True, upload_to='video_warning/alerts/%Y_%m_%d', verbose_name='预警视频')),
                ('strategy', models.TextField(blank=True, null=True, verbose_name='预警策略')),
            ],
            options={
                'verbose_name': '预警信息',
                'verbose_name_plural': '预警信息',
                'ordering': ('-publishDate',),
            },
        ),
    ]
