# Generated by Django 5.1.4 on 2025-04-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realApp', '0003_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='short_message',
            field=models.CharField(default='', max_length=30, verbose_name='短信通知'),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='strategy',
            field=models.TextField(blank=True, null=True, verbose_name='采取策略'),
        ),
    ]
