# Generated by Django 5.1.4 on 2025-04-19 22:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realApp', '0004_alerts_short_message_alter_alerts_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '跌倒'), (2, '捂胸口'), (3, '扶墙'), (4, '其他')], default=1, verbose_name='预警类型')),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '行为状态变化',
                'verbose_name_plural': '行为状态变化',
                'ordering': ('-publishDate',),
            },
        ),
        migrations.CreateModel(
            name='EmotionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '平静'), (2, '喜悦'), (3, '痛苦悲伤')], default=1, verbose_name='预警类型')),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '情绪状态变化',
                'verbose_name_plural': '情绪状态变化',
                'ordering': ('-publishDate',),
            },
        ),
    ]
