# Generated by Django 5.1.4 on 2025-04-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realApp', '0005_behaviorchange_emotionchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='contact/recruit/%Y_%m_%d', verbose_name='个人照片'),
        ),
    ]
