# Generated by Django 5.1.4 on 2025-04-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realApp', '0006_alter_resume_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP_Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('ip', models.CharField(max_length=20, verbose_name='IP地址')),
            ],
            options={
                'verbose_name': 'IP配置',
                'verbose_name_plural': 'IP配置',
            },
        ),
    ]
